### ISSUE TITLE
是否有开源协议？

### ISSUE THREAD

**Issue by Sun-ZhenXing** [nanxiaoshu/win10#1]
作者是否允许二次开发，并重新分发？
希望作者给一个开源协议加以保护，以方便个人二次使用。

——来自b站，感谢作者7天的忙碌😁

**Comment by nanxiaoshu** [comment]
这段在准备面试相关的东西，我还有很多想法还没来得及去实现。
如果您现在就想使用的话，稍后我将开源协议补上。

**Comment by Sun-ZhenXing** [comment]
你可以简单说明你想用什么来开源，之后再补上也可以。

**Comment by nanxiaoshu** [comment]
我已经上传了。
wish you happy coding
